spring.application.name=taskflow-backend

# Configurações de Banco de Dados (Supabase - IPv4 via Pooler)
# Forçando a conexão via porta 6543 (Pooler) que suporta IPv4
spring.datasource.url=jdbc:postgresql://db.gackvwuokitcfvkrgngt.supabase.co:6543/postgres?sslmode=require&prepareThreshold=0
# O usuário DEVE ter o ID do projeto no final para o Pooler funcionar: postgres.[ID]
spring.datasource.username=postgres.gackvwuokitcfvkrgngt
spring.datasource.password=ACeVwrBDv9hNgSbU
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080
