spring.application.name=taskflow-backend

# Configurações de Banco de Dados (Supabase - PostgreSQL)
spring.datasource.url=jdbc:postgresql://db.gackvwuokitcfvkrgngt.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=ACeVwrBDv9hNgSbU
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Pool (Hikari) para evitar timeouts no deploy
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# JPA/Hibernate - Forçando o dialeto para evitar erro de detecção de metadados
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080
